config/routes.rb
Rails.application.routes.draw do

  shallow do
    resources :users, :constraints => { :id => /.*/ } do # allow dots in URLs for querying by email
      resources :playlists do
        resources :tracks
      end
    end
  end

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  get '/uploads/grid/user/avatar/:id/:filename' => 'users#avatar', :via => [:get], :as => 'gridfs_avatar'

  root 'sessions#new'

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Slug

  has_many :playlists, dependent: :destroy

  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :github, type: String
  field :linkedin, type: String

  mount_uploader :avatar, AvatarUploader

  slug do |cur_object|
    cur_object.email
  end

  def public_playlists
    playlists.select(&:public?)
  end

  def private_playlists
    playlists.reject(&:public?)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :avatar]
  skip_before_filter :require_user, :only => [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def avatar
    content = @user.avatar.read
    send_data content, type: @user.avatar.file.content_type, disposition: 'inline'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :github, :linkedin, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :github %><br>
    <%= f.text_field :github %>
  </div>
  <div class="field">
    <%= f.label :linkedin %><br>
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/users/_user_playlists.html.erb
<ul>
    <% playlists.each do |playlist| %>
        <li>
            <%= link_to playlist.title, playlist_path(playlist) %> |
            <%= link_to 'Edit', edit_playlist_path(playlist) %>
            <%= link_to 'Delete', playlist_path(playlist), method: :delete %>
        </li>
    <% end %>
</ul>

app/views/users/edit.html.erb
<h1>Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hello, <%= @user.first_name %>!</strong>
</p>

<% unless @user.avatar.url.nil? %>
    <%= image_tag(@user.avatar.url, height: '75', width: '75') %>
<% end %>

<div>
    <strong>You social links:</strong>
    <% if @user.github.blank? && @user.linkedin.blank? %>
        None yet.
        <%= link_to 'Update your profile', edit_user_path(@user) %>
        to add your LinkedIn and Github links!
    <% else %>
        <ul>
            <% unless @user.github.blank? %>
                <li>
                    <%= link_to 'Github', @user.github %>
                </li>
            <% end %>
            <% unless @user.linkedin.blank? %>
                <li>
                    <%= link_to 'LinkedIn', @user.linkedin %>
                </li>
            <% end %>
        </ul>
    <% end %>
</div>

<div>
    <% if !@user.playlists.empty? %>
      <strong>Your Public Playlists:</strong>
      <% if @user.public_playlists.empty? %>
        None yet.
      <% else %>
        <%= render partial: 'user_playlists', locals: { playlists: @user.public_playlists } %>
      <% end %>

      <strong>Your Private Playlists:</strong>
      <% if @user.private_playlists.empty? %>
        None yet.
      <% else %>
        <%= render partial: 'user_playlists', locals: { playlists: @user.private_playlists } %>
      <% end %>

        <%= link_to 'Create new playlist', new_user_playlist_path(@user) %>
    <% else %>
        It looks like you have no playlists yet.
        <%= link_to 'Click here to create some!', new_user_playlist_path(@user) %>
    <% end %>
</div>


<%= link_to 'Edit Profile', edit_user_path(@user) %>