config/routes.rb
Rails.application.routes.draw do

  shallow do
    resources :users, :constraints => { :id => /.*/ } do # allow dots in URLs for querying by email
      resources :playlists do
        resources :tracks
      end
    end
  end

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', :as => 'logout'

  get '/uploads/grid/user/avatar/:id/:filename' => 'users#avatar', :via => [:get], :as => 'gridfs_avatar'

  root 'sessions#new'

end

app/models/playlist.rb
class Playlist
  include Mongoid::Document
  include Mongoid::Slug

  field :title, type: String
  field :public, type: Boolean, default: false
  alias :public? :public

  slug :title

  has_many :tracks, dependent: :destroy

  belongs_to :user

  validates :title, presence: true
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  before_action :load_user, only: [:new, :create]
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  skip_before_action :require_user, :only => [:show]

  def new
    @playlist = @user.playlists.new
  end

  def create
    @playlist = @user.playlists.new(playlist_params)
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlist_path(@playlist), notice: 'Playlist created' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    redirect_to root_url unless logged_in? || @playlist.public?
    @playlist
  end

  def edit
  end

  def share
    @playlist.public = true
    @playlist.update
  end

  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to playlist_path, notice: 'Playlist updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@playlist.user), notice: 'Playlist destroyed' }
      format.json { head :no_content }
    end
  end

  private

  def load_user
    @user = User.find(params[:user_id])
  end

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:title, :type, :public)
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for([@user, @playlist]) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, 'error') %> prohibited this user from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :public? %><br>
    <%= f.check_box :public %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit <%= @playlist.title %> </h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@playlist.user) %> |
<%= link_to 'Delete', playlist_path(@playlist), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form' %>

<%= link_to 'back', user_path(@user) %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Playlist:</strong>
  <%= @playlist.title + "#{!logged_in? ? ' by ' + @playlist.user.first_name : ''}" %>
</p>

<div>
  <strong>Tracks:</strong>
    <ul>
        <% @playlist.tracks.each do |track| %>
            <li>
                <%= link_to "#{track.title} - #{track.artist}", track.link %> |
                <%= link_to 'Edit', edit_track_path(track) %>
                <%= link_to 'Delete', track_path(track), method: :delete %>
            </li>
        <% end %>
    </ul>
</div>

<% if logged_in? %>
    <%= link_to 'Add Track', new_playlist_track_path(@playlist) %> |
    <%= link_to 'Back', user_path(@playlist.user) %>
<% end %>